apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: upload-convert-to-pdf
  namespace: fyllut-sendinn
  labels:
    team: fyllut-sendinn
  annotations:
    nais.io/run-as-user: "1001"
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/fyllut-sendinn/upload-convert-to-pdf:8.0.0

  command:
    - "gotenberg"
    - "--api-disable-health-check-logging"
    - "--libreoffice-auto-start"
    - "--webhook-disable"
  port: 3000

  liveness:
    path: /health
    initialDelay: 60
    timeout: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /prometheus/metrics

  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}

  accessPolicy:
    inbound:
      rules:
      {{#each accessPolicyInbound.current-namespace}}
        - application: "{{this}}"
      {{/each}}
      {{#each accessPolicyInbound.other-namespace}}
        - application: "{{this.application}}"
          namespace: "{{this.namespace}}"
       {{/each}}

  replicas:
    min: 2
    max: 4
  resources:
    # for lite ressurser allokert kan føre til 503: Service Unavailable fra applikasjonen skjedde med cpu: 200m / mem: 500Mi
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi