apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: upload-convert-to-pdf
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nais.io/run-as-user: "1001"
spec:
  image: ghcr.io/navikt/sosialhjelp-konvertering-til-pdf/gotenberg:8.0.0
  command:
    - "gotenberg"
    - "--api-disable-health-check-logging"
    - "--libreoffice-auto-start"
    - "--webhook-disable"
  port: 3000
  liveness:
    path: /health
    initialDelay: 60
    timeout: 5
    failureThreshold: 10
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  accessPolicy:
    inbound:
      rules:
      {{#each accessPolicyInbound.current-namespace}}
        - application: "{{this}}"
      {{/each}}
      {{#each accessPolicyInbound.other-namespace}}
        - application: "{{this.application}}"
          namespace: "{{this.namespace}}"
       {{/each}}
  replicas:
    min: 1
    max: 4
  resources:
    # for lite ressurser allokert kan føre til 503: Service Unavailable fra applikasjonen skjedde med cpu: 200m / mem: 500Mi
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi