name: Deploy to dev-gcp

on:
  workflow_dispatch:

permissions:
  contents: "write"
  id-token: "write"

jobs:
  deploy:
    name: "Deploy to NAIS"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yaml
